version: '3'
services:

  php:
    build: ./php
    container_name: php
    restart: always
    volumes:
      - ./php/www/:/var/www/html
    links:
      - db
    ports:
      - 80:80
    environment:
      - TZ=Asia/Bangkok

  db:
    image: mysql:latest
    container_name: db
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootp@ssw0rd
      - MYSQL_DATABASE=test
      - MYSQL_USER=jesse
      - MYSQL_PASSWORD=p@ssw0rd
      - TZ=Asia/Bangkok

  node:
    restart: always
    build: ./node_app
    container_name: node_server
    volumes:
      - ./node_app:/src/app
    ports:
      - '8100:3000'
    links:
      - db
    environment:
      - TZ=Asia/Bangkok
