version: '2'
services:

  php:
    build: ./
    container_name: lemp_php7_apache
    restart: always
    volumes:
      - ./php/www/:/var/www/html
    ports:
      - 80:80
    environment:
      - TZ=Asia/Bangkok

  db:
    image: mariadb:latest
    container_name: lemp_mariadb
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./mysql/initdb/:/docker-entrypoint-initdb.d
      - ./mysql/data/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootp@ssw0rd
      - MYSQL_DATABASE=test
      - MYSQL_USER=jesse
      - MYSQL_PASSWORD=p@ssw0rd
      - TZ=Asia/Bangkok

  node_server:
    restart: always
    build: ./node_app
    container_name: node_server
    volumes:
      - ./node_app:/src/app
    ports:
      - '8100:3000'
    environment:
      - TZ=Asia/Bangkok
